### ISSUE TITLE
Scoreboard command [bug]

### ISSUE THREAD

**Issue by MarkFazekas** [GlowstoneMC/Glowstone-Legacy#626] opened 2015-02-08 00:24 UTC
01:18:14 [INFO] OxoniumX issued command: /scoreboard teams
01:18:14 [SEVERE] Exception while executing command: /scoreboard teams
org.bukkit.command.CommandException: Unhandled exception executing 'scoreboard t
eams' in org.bukkit.command.defaults.ScoreboardCommand(scoreboard)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:18
4)
        at net.glowstone.GlowServer.dispatchCommand(GlowServer.java:1055)
        at net.glowstone.entity.GlowPlayer$2.run(GlowPlayer.java:1297)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at net.glowstone.scheduler.GlowTask.run(GlowTask.java:163)
        at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:182)
        at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:2
5)
        at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:111)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at org.bukkit.command.defaults.ScoreboardCommand.execute(ScoreboardComma
nd.java:80)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:18
0)
        ... 15 more

**Comment by PaulBGD** [comment] 2015-02-08 01:00
Scoreboards are not implemented.

**Comment by turt2live** [comment] 2015-02-08 01:47
Closing as a duplicate of #81 (currently implementation is #459)

**Closed as completed by turt2live** 2015-02-08 01:47 UTC
