### ISSUE TITLE
Bonemeal on sapling does not work.

### ISSUE THREAD

**Issue by Maxiebyte** [GlowstoneMC/Glowstone-Legacy#628] opened 2015-02-20 16:05 UTC
![2015-02-20_16 49 08](https://cloud.githubusercontent.com/assets/7554210/6289436/7ed1d2a4-b920-11e4-9de7-b9d189fb1433.png)

I was trying to do some things on the Glowstone public test server and I noticed that using bonemeal on saplings does not work.
I tried to grow a big jungle tree (four saplings in a square + bonemeal) but that didn't work
I couldn't find code in the Glowstone repository https://github.com/GlowstoneMC/Glowstone/search?utf8=%E2%9C%93&q=sapling that handles bonemeal interaction with saplings.
#432 adds support for bonemeal interaction but trees should grow automatic.

http://minecraft.gamepedia.com/Tree#Growth_and_characteristics

**Comment by jimmikaelkael** [comment] 2015-02-20 16:30
Automatic growth would mean block ticking is implemented. This isn't the case actually.

**Comment by dequis** [comment] 2015-02-20 18:09
Dupe of #325 for bonemeal interaction, dunno what issue for block ticking

**Comment by Maxiebyte** [comment] 2015-02-20 18:29
I didn't notice #325.

**Comment by turt2live** [comment] 2015-02-26 13:59
Closing as duplicate. #431 handles block ticking, ticket #40.

**Closed as completed by turt2live** 2015-02-26 13:59 UTC
