### ISSUE TITLE
enable bone enable auto trees

### ISSUE THREAD

**Issue by GRezende01** [GlowstoneMC/Glowstone-Legacy#616] opened 2015-01-18 09:32 UTC
must enable the mobs and bone meal , and enable self cresimento trees

**Comment by turt2live** [comment] 2015-01-18 09:38
Closing as a duplicate of the following:
- #40 for what I think you mean by "self _cresimento_ trees"
- #139 for mobs
- #325 for bone meal

**Closed as completed by turt2live** 2015-01-18 09:38 UTC
